-- AlterTable
ALTER TABLE `dateevent` MODIFY `type` ENUM('VISIT', 'EVENT', 'OTHER', 'BARTER', 'OVERNIGHT', 'PRODUCTION') NOT NULL;

-- AlterTable
ALTER TABLE `notification` MODIFY `type` ENUM('VISIT', 'EVENT', 'ALERT', 'OTHER', 'BARTER', 'PROPOSAL', 'OVERNIGHT', 'PRODUCTION') NOT NULL;
